apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: orders-api
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  definition: |
    openapi: 3.0.3
    info:
      title: Orders API
      version: 1.0.0
    paths:
      /orders:
        get:
          responses:
            '200':
              description: OK
        post:
          responses:
            '201':
              description: Created
