apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-get-api
  description: Demo GET-only API docs (Petstore)
  tags: [demo, external, get]
spec:
  type: openapi
  lifecycle: production
  owner: api-platform
  definition:
    $openapi: https://petstore3.swagger.io/api/v3/openapi.json
